/* tslint:disable */
/* eslint-disable */
/**
 * BadBot API
 * API for BadBot service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AuthRequest } from '../models';
// @ts-ignore
import type { AuthResponse } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { ProcessTweetsRequest } from '../models';
// @ts-ignore
import type { ProcessTweetsResponse } from '../models';
// @ts-ignore
import type { WhitelistedUsersResponse } from '../models';
/**
 * PublicApiApi - axios parameter creator
 * @export
 */
export const PublicApiApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get the list of users that are currently whitelisted (verified humans).
         * @summary Get Whitelisted Users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWhitelistedUsersApiWhitelistedUsersGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/whitelisted-users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Process a list of tweet URLs, extracting tweet IDs and validating the URLs.
         * @summary Process Tweets
         * @param {ProcessTweetsRequest} processTweetsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        processTweetsApiProcessTweetsPost: async (processTweetsRequest: ProcessTweetsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'processTweetsRequest' is not null or undefined
            assertParamExists('processTweetsApiProcessTweetsPost', 'processTweetsRequest', processTweetsRequest)
            const localVarPath = `/api/process-tweets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(processTweetsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Verify user authentication with email and password, and generate a new API key.
         * @summary Verify Auth
         * @param {AuthRequest} authRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyAuthApiAuthVerifyPost: async (authRequest: AuthRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authRequest' is not null or undefined
            assertParamExists('verifyAuthApiAuthVerifyPost', 'authRequest', authRequest)
            const localVarPath = `/api/auth/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PublicApiApi - functional programming interface
 * @export
 */
export const PublicApiApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PublicApiApiAxiosParamCreator(configuration)
    return {
        /**
         * Get the list of users that are currently whitelisted (verified humans).
         * @summary Get Whitelisted Users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWhitelistedUsersApiWhitelistedUsersGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WhitelistedUsersResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWhitelistedUsersApiWhitelistedUsersGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PublicApiApi.getWhitelistedUsersApiWhitelistedUsersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Process a list of tweet URLs, extracting tweet IDs and validating the URLs.
         * @summary Process Tweets
         * @param {ProcessTweetsRequest} processTweetsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async processTweetsApiProcessTweetsPost(processTweetsRequest: ProcessTweetsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProcessTweetsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.processTweetsApiProcessTweetsPost(processTweetsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PublicApiApi.processTweetsApiProcessTweetsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Verify user authentication with email and password, and generate a new API key.
         * @summary Verify Auth
         * @param {AuthRequest} authRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verifyAuthApiAuthVerifyPost(authRequest: AuthRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.verifyAuthApiAuthVerifyPost(authRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PublicApiApi.verifyAuthApiAuthVerifyPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PublicApiApi - factory interface
 * @export
 */
export const PublicApiApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PublicApiApiFp(configuration)
    return {
        /**
         * Get the list of users that are currently whitelisted (verified humans).
         * @summary Get Whitelisted Users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWhitelistedUsersApiWhitelistedUsersGet(options?: RawAxiosRequestConfig): AxiosPromise<WhitelistedUsersResponse> {
            return localVarFp.getWhitelistedUsersApiWhitelistedUsersGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Process a list of tweet URLs, extracting tweet IDs and validating the URLs.
         * @summary Process Tweets
         * @param {ProcessTweetsRequest} processTweetsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        processTweetsApiProcessTweetsPost(processTweetsRequest: ProcessTweetsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ProcessTweetsResponse> {
            return localVarFp.processTweetsApiProcessTweetsPost(processTweetsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Verify user authentication with email and password, and generate a new API key.
         * @summary Verify Auth
         * @param {AuthRequest} authRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyAuthApiAuthVerifyPost(authRequest: AuthRequest, options?: RawAxiosRequestConfig): AxiosPromise<AuthResponse> {
            return localVarFp.verifyAuthApiAuthVerifyPost(authRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PublicApiApi - object-oriented interface
 * @export
 * @class PublicApiApi
 * @extends {BaseAPI}
 */
export class PublicApiApi extends BaseAPI {
    /**
     * Get the list of users that are currently whitelisted (verified humans).
     * @summary Get Whitelisted Users
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PublicApiApi
     */
    public getWhitelistedUsersApiWhitelistedUsersGet(options?: RawAxiosRequestConfig) {
        return PublicApiApiFp(this.configuration).getWhitelistedUsersApiWhitelistedUsersGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Process a list of tweet URLs, extracting tweet IDs and validating the URLs.
     * @summary Process Tweets
     * @param {ProcessTweetsRequest} processTweetsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PublicApiApi
     */
    public processTweetsApiProcessTweetsPost(processTweetsRequest: ProcessTweetsRequest, options?: RawAxiosRequestConfig) {
        return PublicApiApiFp(this.configuration).processTweetsApiProcessTweetsPost(processTweetsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Verify user authentication with email and password, and generate a new API key.
     * @summary Verify Auth
     * @param {AuthRequest} authRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PublicApiApi
     */
    public verifyAuthApiAuthVerifyPost(authRequest: AuthRequest, options?: RawAxiosRequestConfig) {
        return PublicApiApiFp(this.configuration).verifyAuthApiAuthVerifyPost(authRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

