/* tslint:disable */
/* eslint-disable */
/**
 * BadBot API
 * API for BadBot service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthResponse
 */
export interface AuthResponse {
    /**
     * 
     * @type {boolean}
     * @memberof AuthResponse
     */
    'success': boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    'user_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    'api_key'?: string | null;
}

