/* tslint:disable */
/* eslint-disable */
/**
 * Good Replies API
 * API for Good Replies service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PydanticValidationError } from './pydantic-validation-error';

/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<PydanticValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<PydanticValidationError>;
}

