/* tslint:disable */
/* eslint-disable */
/**
 * BadBot API
 * API for BadBot service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TweetProcessingResult } from './tweet-processing-result';

/**
 * 
 * @export
 * @interface ProcessTweetsResponse
 */
export interface ProcessTweetsResponse {
    /**
     * 
     * @type {Array<TweetProcessingResult>}
     * @memberof ProcessTweetsResponse
     */
    'results': Array<TweetProcessingResult>;
    /**
     * 
     * @type {number}
     * @memberof ProcessTweetsResponse
     */
    'successfully_processed': number;
    /**
     * 
     * @type {number}
     * @memberof ProcessTweetsResponse
     */
    'failed_to_process': number;
}

