/* tslint:disable */
/* eslint-disable */
/**
 * Good Replies API
 * API for Good Replies service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProcessTweetsRequest
 */
export interface ProcessTweetsRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof ProcessTweetsRequest
     */
    'tweet_urls': Array<string>;
}

