/* tslint:disable */
/* eslint-disable */
/**
 * Good Replies API
 * API for Good Replies service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WhitelistedUser
 */
export interface WhitelistedUser {
    /**
     * 
     * @type {number}
     * @memberof WhitelistedUser
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof WhitelistedUser
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof WhitelistedUser
     */
    'platform': string;
    /**
     * 
     * @type {string}
     * @memberof WhitelistedUser
     */
    'display_name': string | null;
    /**
     * 
     * @type {number}
     * @memberof WhitelistedUser
     */
    'follower_count': number | null;
    /**
     * 
     * @type {number}
     * @memberof WhitelistedUser
     */
    'verification_score': number | null;
    /**
     * 
     * @type {string}
     * @memberof WhitelistedUser
     */
    'linked_at': string;
}

