/* tslint:disable */
/* eslint-disable */
/**
 * BadBot API
 * API for BadBot service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WhitelistedUser } from './whitelisted-user';

/**
 * 
 * @export
 * @interface WhitelistedUsersResponse
 */
export interface WhitelistedUsersResponse {
    /**
     * 
     * @type {Array<WhitelistedUser>}
     * @memberof WhitelistedUsersResponse
     */
    'users': Array<WhitelistedUser>;
    /**
     * 
     * @type {number}
     * @memberof WhitelistedUsersResponse
     */
    'total_count': number;
}

